services:
  - type: web
    name: rms-backend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        value: 153.92.15.31
      - key: DB_USER
        value: u875409848_estorco
      - key: DB_PASSWORD
        value: Y9Lq>$f$Q1
      - key: DB_NAME
        value: u875409848_estorco
      - key: DB_PORT
        value: 3306
      - key: JWT_SECRET
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: 
    healthCheckPath: /health
    autoDeploy: true
    branch: main
